
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int prPotencia = 30;
  public static final int tpuntoycoma = 7;
  public static final int prHasta = 53;
  public static final int prFinMientras = 57;
  public static final int prIngresar = 32;
  public static final int tigual = 22;
  public static final int tparC = 15;
  public static final int prEsDiferente = 41;
  public static final int tparA = 14;
  public static final int prMetodo = 61;
  public static final int prFinSi = 46;
  public static final int prOR = 42;
  public static final int tcorC = 17;
  public static final int tvariable = 3;
  public static final int tcorA = 16;
  public static final int prConParametros = 62;
  public static final int prFuncion = 64;
  public static final int prRetornar = 60;
  public static final int tmultiplicacion = 11;
  public static final int prEjecutar = 66;
  public static final int tmodulo = 13;
  public static final int prFinPara = 54;
  public static final int tcadena = 8;
  public static final int prDeloContrario = 48;
  public static final int tsuma = 9;
  public static final int prMenor = 37;
  public static final int tdivision = 12;
  public static final int prMayor = 36;
  public static final int tflecha = 19;
  public static final int prImprimir = 67;
  public static final int numero = 2;
  public static final int prImprimirNl = 68;
  public static final int prNOT = 44;
  public static final int prAND = 43;
  public static final int tcoma = 6;
  public static final int prVerdadero = 25;
  public static final int prConValor = 34;
  public static final int prEsIGUAL = 40;
  public static final int tpunto = 5;
  public static final int prHastaQue = 59;
  public static final int EOF = 0;
  public static final int prEntonces = 45;
  public static final int prCadena = 29;
  public static final int prComo = 33;
  public static final int prIncremental = 55;
  public static final int error = 1;
  public static final int prBoolean = 24;
  public static final int prFinFuncion = 65;
  public static final int prFalso = 26;
  public static final int prSegun = 49;
  public static final int prSi = 35;
  public static final int prHacer = 50;
  public static final int prFin = 69;
  public static final int prCaracter = 27;
  public static final int tguionBajo = 18;
  public static final int prMientras = 56;
  public static final int tinterrogacionc = 21;
  public static final int tinterrogaciona = 20;
  public static final int tcaracter = 4;
  public static final int prOSi = 47;
  public static final int prFinSegun = 51;
  public static final int prMenorIgual = 39;
  public static final int prInicio = 23;
  public static final int prRepetir = 58;
  public static final int tresta = 10;
  public static final int prFinMetodo = 63;
  public static final int prMod = 31;
  public static final int prNumero = 28;
  public static final int prPara = 52;
  public static final int prMayorIgual = 38;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "numero",
  "tvariable",
  "tcaracter",
  "tpunto",
  "tcoma",
  "tpuntoycoma",
  "tcadena",
  "tsuma",
  "tresta",
  "tmultiplicacion",
  "tdivision",
  "tmodulo",
  "tparA",
  "tparC",
  "tcorA",
  "tcorC",
  "tguionBajo",
  "tflecha",
  "tinterrogaciona",
  "tinterrogacionc",
  "tigual",
  "prInicio",
  "prBoolean",
  "prVerdadero",
  "prFalso",
  "prCaracter",
  "prNumero",
  "prCadena",
  "prPotencia",
  "prMod",
  "prIngresar",
  "prComo",
  "prConValor",
  "prSi",
  "prMayor",
  "prMenor",
  "prMayorIgual",
  "prMenorIgual",
  "prEsIGUAL",
  "prEsDiferente",
  "prOR",
  "prAND",
  "prNOT",
  "prEntonces",
  "prFinSi",
  "prOSi",
  "prDeloContrario",
  "prSegun",
  "prHacer",
  "prFinSegun",
  "prPara",
  "prHasta",
  "prFinPara",
  "prIncremental",
  "prMientras",
  "prFinMientras",
  "prRepetir",
  "prHastaQue",
  "prRetornar",
  "prMetodo",
  "prConParametros",
  "prFinMetodo",
  "prFuncion",
  "prFinFuncion",
  "prEjecutar",
  "prImprimir",
  "prImprimirNl",
  "prFin"
  };
}

