
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int prPotencia = 26;
  public static final int tpuntoycoma = 5;
  public static final int prHasta = 41;
  public static final int prFinMientras = 45;
  public static final int prIngresar = 28;
  public static final int tigual = 19;
  public static final int tparC = 14;
  public static final int tparA = 13;
  public static final int prMetodo = 49;
  public static final int prFinSi = 34;
  public static final int prConParametros = 50;
  public static final int prFuncion = 52;
  public static final int prRetornar = 48;
  public static final int tmultiplicacion = 10;
  public static final int prEjecutar = 54;
  public static final int tmodulo = 12;
  public static final int prFinPara = 42;
  public static final int prDeloContrario = 36;
  public static final int tsuma = 8;
  public static final int tdivision = 11;
  public static final int tflecha = 16;
  public static final int prImprimir = 55;
  public static final int numero = 6;
  public static final int prImprimirNl = 56;
  public static final int tcoma = 4;
  public static final int Cadena = 7;
  public static final int prVerdadero = 22;
  public static final int prConValor = 30;
  public static final int var = 2;
  public static final int tpunto = 3;
  public static final int prEsIGUAL = 32;
  public static final int prHastaQue = 47;
  public static final int EOF = 0;
  public static final int prEntonces = 33;
  public static final int prCadena = 25;
  public static final int prComo = 29;
  public static final int prIncremental = 43;
  public static final int error = 1;
  public static final int prBoolean = 21;
  public static final int prFinFuncion = 53;
  public static final int prFalso = 23;
  public static final int prSegun = 37;
  public static final int prSi = 31;
  public static final int prHacer = 38;
  public static final int prFin = 57;
  public static final int tguionBajo = 15;
  public static final int prMientras = 44;
  public static final int tinterrogacionc = 18;
  public static final int tinterrogaciona = 17;
  public static final int prOSi = 35;
  public static final int prFinSegun = 39;
  public static final int prInicio = 20;
  public static final int prRepetir = 46;
  public static final int tresta = 9;
  public static final int prFinMetodo = 51;
  public static final int prMod = 27;
  public static final int prNumero = 24;
  public static final int prPara = 40;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "var",
  "tpunto",
  "tcoma",
  "tpuntoycoma",
  "numero",
  "Cadena",
  "tsuma",
  "tresta",
  "tmultiplicacion",
  "tdivision",
  "tmodulo",
  "tparA",
  "tparC",
  "tguionBajo",
  "tflecha",
  "tinterrogaciona",
  "tinterrogacionc",
  "tigual",
  "prInicio",
  "prBoolean",
  "prVerdadero",
  "prFalso",
  "prNumero",
  "prCadena",
  "prPotencia",
  "prMod",
  "prIngresar",
  "prComo",
  "prConValor",
  "prSi",
  "prEsIGUAL",
  "prEntonces",
  "prFinSi",
  "prOSi",
  "prDeloContrario",
  "prSegun",
  "prHacer",
  "prFinSegun",
  "prPara",
  "prHasta",
  "prFinPara",
  "prIncremental",
  "prMientras",
  "prFinMientras",
  "prRepetir",
  "prHastaQue",
  "prRetornar",
  "prMetodo",
  "prConParametros",
  "prFinMetodo",
  "prFuncion",
  "prFinFuncion",
  "prEjecutar",
  "prImprimir",
  "prImprimirNl",
  "prFin"
  };
}

